var nccr = {
 	nodes:[
		{nodeName:"Grammar", group:1},
		{nodeName:"Diversification", group:2},
		{nodeName:"Computation", group:3},
		{nodeName:"Reception", group:4},
		{nodeName:"Production", group:5},
		{nodeName:"Variability", group:6},
		{nodeName:"Sociality", group:7},
		{nodeName:"Cooperation", group:8},
		{nodeName:"Digitisation", group:9},
	],
	links:[
		{source:1, target:0, value:5},
		{source:2, target:0, value:2},
		{source:3, target:0, value:5},
		{source:4, target:0, value:3},
		{source:5, target:0, value:1},
		{source:6, target:0, value:3},
		{source:7, target:0, value:2},
		{source:8, target:0, value:0},
		{source:0, target:1, value:5},
		{source:2, target:1, value:2},
		{source:3, target:1, value:2},
		{source:4, target:1, value:1},
		{source:5, target:1, value:0},
		{source:6, target:1, value:3},
		{source:7, target:1, value:3},
		{source:8, target:1, value:0},
		{source:0, target:2, value:2},
		{source:1, target:2, value:2},
		{source:3, target:2, value:3},
		{source:4, target:2, value:4},
		{source:5, target:2, value:1},
		{source:6, target:2, value:1},
		{source:7, target:2, value:0},
		{source:8, target:2, value:1},
		{source:0, target:3, value:5},
		{source:1, target:3, value:2},
		{source:2, target:3, value:3},
		{source:4, target:3, value:8},
		{source:5, target:3, value:3},
		{source:6, target:3, value:1},
		{source:7, target:3, value:2},
		{source:8, target:3, value:2},
		{source:0, target:4, value:3},
		{source:1, target:4, value:1},
		{source:2, target:4, value:4},
		{source:3, target:4, value:8},
		{source:5, target:4, value:4},
		{source:6, target:4, value:1},
		{source:7, target:4, value:1},
		{source:8, target:4, value:4},
		{source:0, target:5, value:1},
		{source:1, target:5, value:0},
		{source:2, target:5, value:1},
		{source:3, target:5, value:3},
		{source:4, target:5, value:4},
		{source:6, target:5, value:1},
		{source:7, target:5, value:0},
		{source:8, target:5, value:5},
		{source:0, target:6, value:3},
		{source:1, target:6, value:3},
		{source:2, target:6, value:1},
		{source:3, target:6, value:1},
		{source:4, target:6, value:1},
		{source:5, target:6, value:1},
		{source:7, target:6, value:7},
		{source:8, target:6, value:2},
		{source:0, target:7, value:2},
		{source:1, target:7, value:3},
		{source:2, target:7, value:0},
		{source:3, target:7, value:2},
		{source:4, target:7, value:1},
		{source:5, target:7, value:0},
		{source:6, target:7, value:7},
		{source:8, target:7, value:3},
		{source:0, target:8, value:0},
		{source:1, target:8, value:0},
		{source:2, target:8, value:1},
		{source:3, target:8, value:2},
		{source:4, target:8, value:4},
		{source:5, target:8, value:5},
		{source:6, target:8, value:2},
		{source:7, target:8, value:3}
	],
};